version = 1

exclude_patterns = [
    "bin/**",
    "**/node_modules/",
    "js/*/*.min.js"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "browser",
    "nodejs"
  ]
  plugins = ["react"]
  style_guide = "airbnb"
